package tapsi.samples.user;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserFormDesign extends CssLayout {
    protected TextField name;
    protected TextField phoneID;
    protected TextField threadID;
    protected ComboBox<Allowance> allowed;
    protected Button save;
    protected Button discard;
    protected Button cancel;
    protected Button delete;

    public UserFormDesign() {
        Design.read(this);
    }
}