package tapsi.samples.crud;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;
import tapsi.samples.backend.data.Availability;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserFormDesign extends CssLayout {
    protected TextField name;
    protected TextField phoneID;
    protected TextField threadID;
    protected ComboBox<Allowance> allowed;
    protected Button save;
    protected Button discard;
    protected Button cancel;
    protected Button delete;

    public UserFormDesign() {
        Design.read(this);
    }
}